version: '3.8'
services:
  backend:
    restart: always
    container_name: backend
    depends_on:
      - mongo
    build:
      context: .
      target: backend
    command: "python main.py"
    ports:
    - 8000:8000
    networks:
      backend:

  mongo:
    restart: always
    image: mongo
    container_name: ${MONGO_HOST:-mongo}
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - ./mongodb-data:/data/db
      - mongodb-config:/data/configdb
    networks:
      - backend

volumes:
  mongodb-data:
  mongodb-config:

networks:
  backend: